Repository SOLPLY/SOLPLY-iOS, pull requests merged in 2025-07, with the labels that each got.

#6 [feat/#3] AppCoordinator 구현
  Solply/Solply/Application/RootView.swift
  Solply/Solply/Application/SolplyApp.swift
  Solply/Solply/Global/Coordinator/AppCoordinator.swift
  Solply/Solply/Global/Coordinator/Destination/AppDestination.swift
  Solply/Solply/Global/Coordinator/Destination/RootDestination.swift
  Solply/Solply/Global/Enum/TabBarState.swift
  Solply/Solply/Global/Modifier/CustomNavigationBarModifier.swift
  Solply/Solply/Global/Modifier/VisibilityModifier.swift
  Solply/Solply/Global/Navigation/TempNavigation.swift
  Solply/Solply/Presentation/ArchiveView/ArchiveView.swift
  Solply/Solply/Presentation/Auth/AuthView.swift
  Solply/Solply/Presentation/ContentView.swift
  Solply/Solply/Presentation/Core/TabBarView.swift
  Solply/Solply/Presentation/Course/CourseDetail/CourseDetailView.swift
  Solply/Solply/Presentation/Course/CourseRecommendView.swift
  Solply/Solply/Presentation/Course/CourseTemp.swift
  Solply/Solply/Presentation/MyPage/MyPageTemp.swift
  Solply/Solply/Presentation/Onboarding/OnboardingTemp.swift
  Solply/Solply/Presentation/Onboarding/OnboardingView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/PlaceDetailView.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/PlaceRecommendView.swift
  Solply/Solply/Presentation/Place/PlaceTemp.swift
  Solply/Solply/Presentation/TabBar/Component/ArchiveButton.swift
  Solply/Solply/Presentation/TabBar/Component/SolplyTabBar.swift
  Solply/Solply/Presentation/TabBar/Component/TabItem.swift
  Solply/Solply/Presentation/TabBar/TabBarView.swift
Labels: 🦒 seungwon, 🛠️ feat

#16 [feat/#15] 네트워크 세팅
  Solply/Solply/Global/Environment/AppEnvironment.swift
  Solply/Solply/Global/Security/KeychainManager.swift
  Solply/Solply/Global/Security/TokenManager.swift
  Solply/Solply/Network/API/TempAPI.swift
  Solply/Solply/Network/Base/BaseResponseBody.swift
  Solply/Solply/Network/Base/BaseService.swift
  Solply/Solply/Network/Base/BaseTargetType.swift
  Solply/Solply/Network/Base/ModelType.swift
  Solply/Solply/Network/DTO/TempDTO.swift
  Solply/Solply/Network/Error/NetworkError.swift
  Solply/Solply/Network/Plugin/MoyaLoggingPlugin.swift
  Solply/Solply/Network/Service/TempService.swift
  Solply/Solply/Network/TargetType/TempTargetType.swift
  Solply/Solply/Network/TempNetwork.swift
Labels: 🦒 seungwon, 🛠️ feat

#18 [feat/#17] 장소상세, 코스 상세 바텀시트에 들어가는 컴포넌트 구현
  Solply/Solply/Global/Component/FindDirectionButton.swift
  Solply/Solply/Global/Component/NMapView.swift
  Solply/Solply/Global/Component/SolplyAddButton.swift
  Solply/Solply/Global/Component/SolplySaveButton.swift
  Solply/Solply/Global/DesignSystem/Assets.xcassets/TempIcon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/TempIcon.imageset/TempIcon.svg
  Solply/Solply/Global/Enum/SolplyContentType.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailAction.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailStore.swift
  Solply/Solply/Presentation/Place/PlaceDetail/PlaceDetailView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailReducer.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailState.swift
Labels: 🦒 seungwon, 🛠️ feat

#22 [feat/#21] 상세 페이지 바텀시트 커스텀 구현
  Solply/Solply/Global/Modifier/DetailBottomSheetModifier.swift
  Solply/Solply/Global/Modifier/SizeStateModifier.swift
  Solply/Solply/Presentation/Place/PlaceDetail/PlaceDetailView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
Labels: 🦒 seungwon, 🛠️ feat

#27 [feat/#26] 코스 상세보기 지도 마커 구현
  Solply/Solply/Global/Component/NMapView.swift
  Solply/Solply/Global/Component/NaverMap/BoundingBox.swift
  Solply/Solply/Global/Component/NaverMap/CourseDetailMapView.swift
  Solply/Solply/Global/Component/NaverMap/MakerManager.swift
  Solply/Solply/Global/Component/NaverMap/MarkerType.swift
  Solply/Solply/Global/Component/NaverMap/ZoomLevel.swift
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker1-default-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker1-default-icon.imageset/Selected=false, num=1.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker1-focused-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker1-focused-icon.imageset/Selected=true, num=1.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker2-default-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker2-default-icon.imageset/Selected=false, num=2.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker2-focused-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker2-focused-icon.imageset/Selected=true, num=2.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker3-default-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker3-default-icon.imageset/Selected=false, num=3.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker3-focused-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker3-focused-icon.imageset/Selected=true, num=3.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker4-default-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker4-default-icon.imageset/Selected=false, num=4.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker4-focused-icon 1.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker4-focused-icon 1.imageset/Selected=true, num=4.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker5-default-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker5-default-icon.imageset/Selected=false, num=5.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker5-focused-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker5-focused-icon.imageset/Selected=true, num=5.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker6-default-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker6-default-icon.imageset/Selected=false, num=6.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker6-focused-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/marker6-focused-icon.imageset/Selected=tru, num=6.svg
  Solply/Solply/Presentation/Course/CourseDetail/CourseDetailView.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailStore.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailState.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Course/CourseRecommend/CourseRecommendView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
  Solply/Solply/Presentation/TempMapView.swift
Labels: 🦒 seungwon, 🛠️ feat

#36 [feat/#34] 지도 선 함수 구현
  Solply/Solply/Global/Component/NaverMap/CourseDetailMapView.swift
Labels: 🦒 seungwon, 🛠️ feat

#35 [feat/#28] 동네 선택 컴포넌트 구현
  Solply/Solply/Global/Component/TownOptionButton.swift
Labels: ☀️ youngju, 🛠️ feat

#39 [fix/#37] font lineHeight 수정
  Solply/Solply/Global/DesignSystem/SolplyFont.swift
Labels: 🦒 seungwon, ✂️ fix

#51 [feat/#49] 아카이브뷰 바 구현
  Solply/Solply/Global/Modifier/CustomNavigationBarModifier.swift
  Solply/Solply/Presentation/Archive/ArchiveIntent/ArchiveAction.swift
  Solply/Solply/Presentation/Archive/ArchiveIntent/ArchiveStore.swift
  Solply/Solply/Presentation/Archive/ArchiveState/ArchiveReducer.swift
  Solply/Solply/Presentation/Archive/ArchiveState/ArchiveState.swift
  Solply/Solply/Presentation/Archive/ArchiveView/ArchiveView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveBar.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveEmptyView.swift
  Solply/Solply/Presentation/ArchiveView/ArchiveView.swift
Labels: 🐳 sooyong, 🛠️ feat

#47 [feat/#44] CTA 버튼 컴포넌트 구현
  Solply/Solply/Global/Component/CTAMainButton.swift
  Solply/Solply/Global/Component/CTASubButton.swift
Labels: ☀️ youngju, 🛠️ feat

#52 [feat/#50] 코스 상세 뷰 (코스추천) 구현
  Solply/Solply/Global/Modifier/DetailBottomSheetModifier.swift
  Solply/Solply/Presentation/Course/Component/DraggablePlaceCell.swift
  Solply/Solply/Presentation/Course/Component/NumberBadge.swift
  Solply/Solply/Presentation/Course/CourseDetail/Effect/CourseDetailEffect.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailStore.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailState.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
Labels: 🦒 seungwon, 📸 add

#61 [feat/#56] 코스 상세 분기 처리 구현
  Solply/Solply/Global/Component/NaverMap/CourseDetailMapView.swift
  Solply/Solply/Global/Coordinator/Destination/AppDestination.swift
  Solply/Solply/Global/Coordinator/Destination/RootDestination.swift
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/drag-drop-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/drag-drop-icon.imageset/drag-drop-icon.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/edit-done-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/edit-done-icon.imageset/edit-done-icon.svg
  Solply/Solply/Presentation/Course/Component/DraggablePlaceCell.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailState.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Course/CourseRecommend/CourseRecommendView.swift
  Solply/Solply/Presentation/Onboarding/Component/ProgressBar.swift
Labels: 🦒 seungwon, 📸 add, 🛠️ feat

#65 [feat/#64] 타운옵션뷰 구현
  Solply/Solply/Global/Component/TownOptionButton.swift
  Solply/Solply/Global/Enum/TownOptionType.swift
  Solply/Solply/Presentation/Onboarding/Component/NicknameView.swift
  Solply/Solply/Presentation/Onboarding/Component/PersonaOptionView.swift
  Solply/Solply/Presentation/Onboarding/Component/TownOptionView.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingAction.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingReducer.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingState.swift
Labels: ☀️ youngju, 🛠️ feat

#73 [feat/#70] 장소 삭제
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/delete-false-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/delete-false-icon.imageset/Hover=false.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/delete-true-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/delete-true-icon.imageset/Hover=true.svg
  Solply/Solply/Global/Enum/DeleteZoneState.swift
  Solply/Solply/Global/Util/DropDelegate.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailState.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
Labels: 🦒 seungwon, 🛠️ feat

#71 [feat/#66] 온보딩뷰 구현 완료
  Solply/Solply/Global/Component/CTAMainButton.swift
  Solply/Solply/Global/Enum/NicknameTextFieldState.swift
  Solply/Solply/Presentation/Onboarding/Component/NicknameTextField.swift
  Solply/Solply/Presentation/Onboarding/Component/NicknameView.swift
  Solply/Solply/Presentation/Onboarding/Component/TownOptionView.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingAction.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingStore.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingReducer.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingState.swift
  Solply/Solply/Presentation/Onboarding/View/OnboardingCompleteView.swift
  Solply/Solply/Presentation/Onboarding/View/OnboardingView.swift
Labels: ☀️ youngju, 🛠️ feat

#79 [feat/#75] Toast 구현
  Solply/Solply/Global/Component/ToastView.swift
  Solply/Solply/Global/Enum/ToastType.swift
  Solply/Solply/Global/Extension/String+.swift
  Solply/Solply/Global/Modifier/ToastModifier.swift
  Solply/Solply/Global/Util/ToastManager.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
Labels: 🦒 seungwon, 🛠️ feat

#81 [feat/#78] custom alert 구현
  Solply/Solply/Global/Enum/AlertType.swift
  Solply/Solply/Global/Modifier/CustomAlertModifier.swift
  Solply/Solply/Presentation/Archive/ArchiveList/Intent/ArchiveListAction.swift
  Solply/Solply/Presentation/Archive/ArchiveList/State/ArchiveListReducer.swift
  Solply/Solply/Presentation/Archive/ArchiveList/State/ArchiveListState.swift
  Solply/Solply/Presentation/Archive/ArchiveList/View/ArchiveListView.swift
Labels: 🐳 sooyong, 🛠️ feat

#82 [feat/#72] 온보딩 컴플리트뷰 구현
  Solply/Solply/Global/Coordinator/AppCoordinator.swift
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image/box-graphic.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image/box-graphic.imageset/box-graphic.svg
  Solply/Solply/Global/Enum/OnboardingStep.swift
  Solply/Solply/Presentation/Onboarding/Component/NicknameView.swift
  Solply/Solply/Presentation/Onboarding/Component/OnboardingCompleteView.swift
  Solply/Solply/Presentation/Onboarding/Effect/OnboardingEffect.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingAction.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingStore.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingReducer.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingState.swift
  Solply/Solply/Presentation/Onboarding/View/OnboardingCompleteView.swift
  Solply/Solply/Presentation/Onboarding/View/OnboardingView.swift
Labels: ☀️ youngju, 🛠️ feat

#87 [feat/#86] 코스 저장 navigate 구현
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
Labels: 🦒 seungwon, 🛠️ feat

#92 [feat/#84] 수집함 네비게이션 구현
  Solply/Solply/Global/Coordinator/Destination/AppDestination.swift
  Solply/Solply/Presentation/Archive/ArchiveList/View/ArchiveListView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveEmptyView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveFullView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveListFullView.swift
Labels: 🐳 sooyong, 🛠️ feat

#95 [feat/#32] 장소 추천 무한 캐러셀 구현
  Solply/Solply.xcodeproj/xcshareddata/xcschemes/Solply.xcscheme
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image/tempImage.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image/tempImage.imageset/tempImage.png
  Solply/Solply/Presentation/Place/Component/TodayPlaceRecommendCard.swift
  Solply/Solply/Presentation/Place/Component/TodayPlaceRecommendCarousel.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Entity/TempPlaceRecommendItem.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Intent/PlaceRecommendAction.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Intent/PlaceRecommendStore.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendReducer.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendState.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/View/PlaceRecommendView.swift
Labels: 🐰 jooyoung, 🛠️ feat

#97 [feat/#96] 장소 카테고리 icon 연산자 프로퍼티 추가
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/unique-icon.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/unique-icon.imageset/special-icon.svg
  Solply/Solply/Global/Enum/PlaceCategoryType.swift
Labels: 🐰 jooyoung, 🛠️ feat

#101 [feat/#90] 스플래시뷰 구현
  Solply/Solply.xcodeproj/project.pbxproj
  Solply/Solply.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Solply/Solply/Global/Coordinator/AppCoordinator.swift
  Solply/Solply/Global/Coordinator/Destination/RootDestination.swift
  Solply/Solply/Global/DesignSystem/Lottie/Splash.json
  Solply/Solply/Presentation/Onboarding/Component/OnboardingCompleteView.swift
  Solply/Solply/Presentation/Splash/LottieView.swift
  Solply/Solply/Presentation/Splash/SplashView.swift
Labels: ☀️ youngju, 🛠️ feat

#111 [feat/#94] 수집함 애니메이션 추가 및 스와이프 구현
  Solply/Solply/Global/Enum/PlaceCategoryType.swift
  Solply/Solply/Presentation/Archive/Archive/View/ArchiveView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveBar.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveEmptyView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveFullView.swift
Labels: 🐳 sooyong, 🛠️ feat

#126 [feat/#123] 코스 메인 뷰 구현
  Solply/Solply/Presentation/Course/Component/CourseRecommendGrid.swift
  Solply/Solply/Presentation/Course/CourseRecommend/CourseRecommendView.swift
  Solply/Solply/Presentation/Course/CourseRecommend/Intent/CourseRecommendAction.swift
  Solply/Solply/Presentation/Course/CourseRecommend/Intent/CourseRecommendStore.swift
  Solply/Solply/Presentation/Course/CourseRecommend/State/CourseRecommendReducer.swift
  Solply/Solply/Presentation/Course/CourseRecommend/State/CourseRecommendState.swift
  Solply/Solply/Presentation/Course/CourseRecommend/View/CourseRecommendView.swift
  Solply/Solply/Presentation/Place/Component/FilterPlaceGrid.swift
Labels: 🐰 jooyoung, 🛠️ feat

#128 [docs/#127] readme 파일 작성
  README.md
Labels: ☀️ youngju, 📚 docs

#136 [feat/#134] OnboardingCompleteView Lottie 구현
  Solply/Solply/Global/DesignSystem/Lottie/finishOnboarding.json
  Solply/Solply/Presentation/Onboarding/Component/OnboardingCompleteView.swift
Labels: ☀️ youngju, 🛠️ feat

#137 [feat/#133] TabbarView -> FrequentTownView 이동 구현
  Solply/Solply/Global/Coordinator/Destination/AppDestination.swift
  Solply/Solply/Presentation/Course/CourseRecommend/View/CourseRecommendView.swift
  Solply/Solply/Presentation/FrequentTown/Intent/FrequentTownAction.swift
  Solply/Solply/Presentation/FrequentTown/Intent/FrequentTownStore.swift
  Solply/Solply/Presentation/FrequentTown/State/FrequentTownReducer.swift
  Solply/Solply/Presentation/FrequentTown/State/FrequentTownState.swift
  Solply/Solply/Presentation/FrequentTown/View/FrequentTownView.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/View/PlaceRecommendView.swift
  Solply/Solply/Presentation/TabBar/TabBarView.swift
Labels: 🐰 jooyoung, 🛠️ feat

#139 [feat/#135] 내 코스 추가하기 수집함 API 구현
  Solply/Solply/Global/Enum/PlaceCategoryType.swift
  Solply/Solply/Global/Util/DropDelegate.swift
  Solply/Solply/Network/API/CourseDetailAPI.swift
  Solply/Solply/Network/API/PlaceDetailAPI.swift
  Solply/Solply/Network/Base/BaseTargetType.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseArchiveResponseDTO.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseDetailResponseDTO.swift
  Solply/Solply/Network/DTO/TempDTO.swift
  Solply/Solply/Network/Service/AuthService.swift
  Solply/Solply/Network/Service/CourseService.swift
  Solply/Solply/Network/Service/OnboardingService.swift
  Solply/Solply/Network/Service/PlaceService.swift
  Solply/Solply/Network/Service/RecommendService.swift
  Solply/Solply/Network/Service/TagService.swift
  Solply/Solply/Network/Service/TownService.swift
  Solply/Solply/Network/Service/UserService.swift
  Solply/Solply/Network/TargetType/AuthTargetType.swift
  Solply/Solply/Network/TargetType/CourseTargetType.swift
  Solply/Solply/Network/TargetType/OnboardingTargetType.swift
  Solply/Solply/Network/TargetType/PlaceTargetType.swift
  Solply/Solply/Network/TargetType/TagTargetType.swift
  Solply/Solply/Network/TargetType/TempTargetType.swift
  Solply/Solply/Network/TargetType/TownTargetType.swift
  Solply/Solply/Network/TargetType/UserTargetType.swift
  Solply/Solply/Presentation/Auth/Effect/AuthEffect.swift
  Solply/Solply/Presentation/Auth/State/AuthReducer.swift
  Solply/Solply/Presentation/Course/Component/CourseDetailMapView.swift
  Solply/Solply/Presentation/Course/CourseDetail/Effect/CourseDetailEffect.swift
  Solply/Solply/Presentation/Course/CourseDetail/Entity/CourseDetail.swift
  Solply/Solply/Presentation/Course/CourseDetail/Entity/TempEntity.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailState.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Place/Component/View/AddPlaceToCourseView.swift
  Solply/Solply/Presentation/Place/Component/View/PlaceDetailMapView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Effect/PlaceDetailEffect.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Entity/PlaceDetail.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailAction.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailStore.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailReducer.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailState.swift
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendState.swift
Labels: 🦒 seungwon, 🛠️ feat

#143 [feat/#141] 코스 상세 API 연동
  Solply/Solply/Global/Enum/DetailBottomSheetState.swift
  Solply/Solply/Global/Util/ZoomLevel.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseDetailResponseDTO.swift
  Solply/Solply/Network/Service/CourseService.swift
  Solply/Solply/Network/TargetType/CourseTargetType.swift
  Solply/Solply/Presentation/Course/CourseDetail/Effect/CourseDetailEffect.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailStore.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Entity/PlaceDetail.swift
Labels: 🦒 seungwon, 🛠️ feat

#145 [feat/#138] 추가 옵션 필터링 구현
  Solply/Solply/Presentation/Place/Component/ChipButtonsContainerView.swift
  Solply/Solply/Presentation/Place/Component/MoreOptionBottomSheet.swift
  Solply/Solply/Presentation/Place/Component/MoreOptionButton.swift
  Solply/Solply/Presentation/Place/Component/MoreOptionChip.swift
  Solply/Solply/Presentation/Place/Component/MoreOptionSection.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendState.swift
Labels: 🐰 jooyoung, 🛠️ feat

#148 [feat/#142] 수집함 장소 썸네일 조회 API 연동
  Solply/Solply/Global/Coordinator/Destination/AppDestination.swift
  Solply/Solply/Network/DTO/Place/ResponseDTO/PlaceArchiveThumbnailResponseDTO.swift
  Solply/Solply/Network/Service/PlaceService.swift
  Solply/Solply/Network/TargetType/PlaceTargetType.swift
  Solply/Solply/Presentation/Archive/Archive/Effect/ArchiveEffect.swift
  Solply/Solply/Presentation/Archive/Archive/Intent/ArchiveAction.swift
  Solply/Solply/Presentation/Archive/Archive/Intent/ArchiveStore.swift
  Solply/Solply/Presentation/Archive/Archive/State/ArchiveReducer.swift
  Solply/Solply/Presentation/Archive/Archive/State/ArchiveState.swift
  Solply/Solply/Presentation/Archive/Archive/View/ArchiveView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveFullView.swift
Labels: 🐳 sooyong, 🛠️ feat

#152 [feat/#150] 코스 상세 장소 단건 저장, 저장 취소 API 연동
  Solply/Solply/Network/Service/PlaceService.swift
  Solply/Solply/Network/TargetType/PlaceTargetType.swift
  Solply/Solply/Presentation/Course/CourseDetail/Effect/CourseDetailEffect.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailStore.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
Labels: 🦒 seungwon, 🛠️ feat

#154 [feat/#147] 추가 옵션 관련 UI 및 기능 추가
  Solply/Solply/Presentation/Place/Component/FilterPlaceGrid.swift
  Solply/Solply/Presentation/Place/Component/MoreOptionBottomSheet.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Intent/PlaceRecommendAction.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendReducer.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendState.swift
Labels: 🐰 jooyoung, 🛠️ feat

#156 [feat/#155] MoreOptionType enum 추가
  Solply/Solply/Global/Enum/MoreOptionType.swift
  Solply/Solply/Global/Enum/PlaceCategoryType.swift
Labels: 🐰 jooyoung, 🛠️ feat

#160 [fix/#159] custom alert 1차 QA 반영
  Solply/Solply/Global/Modifier/CustomAlertModifier.swift
Labels: 🐳 sooyong, ✂️ fix

#165 [feat/#163] 장소 상세 장소 단건 bookmark API 구현
  Solply/Solply/Global/Modifier/DetailBottomSheetModifier.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Effect/PlaceDetailEffect.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailAction.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailStore.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailReducer.swift
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
Labels: 🦒 seungwon, 🛠️ feat

#169 [feat/#167] aligned ScrollView 구현
  Solply/Solply/Presentation/Place/Component/View/PlaceInformationView.swift
Labels: 🦒 seungwon, 🛠️ feat

#176 [feat/#171] 길찾기 구현
  Solply/Solply.xcodeproj/project.pbxproj
  Solply/Solply/Global/Info.plist
  Solply/Solply/Global/Util/LocationManager.swift
  Solply/Solply/Global/Util/NaverMapRouteHelper.swift
  Solply/Solply/Presentation/Course/Component/CourseDetailMapView.swift
  Solply/Solply/Presentation/Course/CourseDetail/Effect/CourseDetailEffect.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailStore.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailState.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Place/Component/View/PlaceDetailMapView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Effect/PlaceDetailEffect.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailAction.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailStore.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailReducer.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailState.swift
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
  Solply/Solply/Presentation/TabBar/TabBarView.swift
Labels: 🦒 seungwon, 🛠️ feat

#179 [feat/#146] OnbaordingView api 구현
  Solply/Solply/Global/Component/TownOptionButton.swift
  Solply/Solply/Global/Enum/TownOptionType.swift
  Solply/Solply/Network/API/OnboardingAPI.swift
  Solply/Solply/Network/API/TownAPI.swift
  Solply/Solply/Network/DTO/Onboarding/RequestDTO/OnboardingRequestDTO.swift
  Solply/Solply/Network/DTO/Onboarding/ResponseDTO/OnboardingResponseDTO.swift
  Solply/Solply/Network/DTO/Town/ResponseDTO/TownResponseDTO.swift
  Solply/Solply/Network/DTO/User/ResponseDTO/UserResponseDTO.swift
  Solply/Solply/Network/Service/OnboardingService.swift
  Solply/Solply/Network/Service/TownService.swift
  Solply/Solply/Network/Service/UserService.swift
  Solply/Solply/Network/TargetType/OnboardingTargetType.swift
  Solply/Solply/Network/TargetType/TownTargetType.swift
  Solply/Solply/Network/TargetType/UserTargetType.swift
  Solply/Solply/Presentation/FrequentTown/Effect/FrequentTownEffect.swift
  Solply/Solply/Presentation/FrequentTown/Intent/FrequentTownAction.swift
  Solply/Solply/Presentation/FrequentTown/Intent/FrequentTownStore.swift
  Solply/Solply/Presentation/FrequentTown/State/FrequentTownReducer.swift
  Solply/Solply/Presentation/FrequentTown/State/FrequentTownState.swift
  Solply/Solply/Presentation/FrequentTown/View/FrequentTownView.swift
  Solply/Solply/Presentation/Onboarding/Component/NicknameTextField.swift
  Solply/Solply/Presentation/Onboarding/Component/NicknameView.swift
  Solply/Solply/Presentation/Onboarding/Component/OnboardingCompleteView.swift
  Solply/Solply/Presentation/Onboarding/Component/PersonaOptionView.swift
  Solply/Solply/Presentation/Onboarding/Component/TownOptionView.swift
  Solply/Solply/Presentation/Onboarding/Effect/OnboardingEffect.swift
  Solply/Solply/Presentation/Onboarding/Entity/OnboardingCompleteInfo.swift
  Solply/Solply/Presentation/Onboarding/Entity/Persona.swift
  Solply/Solply/Presentation/Onboarding/Entity/Town.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingAction.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingStore.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingReducer.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingState.swift
  Solply/Solply/Presentation/Onboarding/View/OnboardingView.swift
Labels: ☀️ youngju, 🛠️ feat

#181 [feat/#178] 수집함 삭제 API 연결
  Solply/Solply/Global/Component/CourseCard.swift
  Solply/Solply/Global/Component/PlaceCard.swift
  Solply/Solply/Network/DTO/Place/ResponseDTO/PlaceArchiveResponseDTO.swift
  Solply/Solply/Network/Service/CourseService.swift
  Solply/Solply/Network/Service/PlaceService.swift
  Solply/Solply/Network/TargetType/CourseTargetType.swift
  Solply/Solply/Network/TargetType/PlaceTargetType.swift
  Solply/Solply/Presentation/Archive/ArchiveList/Effect/ArchiveListEffect.swift
  Solply/Solply/Presentation/Archive/ArchiveList/Intent/ArchiveListAction.swift
  Solply/Solply/Presentation/Archive/ArchiveList/Intent/ArchiveListStore.swift
  Solply/Solply/Presentation/Archive/ArchiveList/State/ArchiveListReducer.swift
  Solply/Solply/Presentation/Archive/ArchiveList/State/ArchiveListState.swift
  Solply/Solply/Presentation/Archive/ArchiveList/View/ArchiveListView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveFullView.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveListFullView.swift
  Solply/Solply/Presentation/Place/Component/FilterPlaceGrid.swift
Labels: 🐳 sooyong, ✂️ fix, 🛠️ feat

#183 [feat/#175] 태그 조회 api 연결
  Solply/Solply.xcodeproj/project.pbxproj
  Solply/Solply/Global/Component/CourseCard.swift
  Solply/Solply/Global/Component/PlaceCard.swift
  Solply/Solply/Global/Component/PlaceCategoryTag.swift
  Solply/Solply/Global/Enum/MainTagType.swift
  Solply/Solply/Global/Enum/MoreOptionType.swift
  Solply/Solply/Global/Enum/SubTagType.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseArchiveResponseDTO.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseDetailResponseDTO.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseRecommendResponseDTO.swift
  Solply/Solply/Network/DTO/Place/ResponseDTO/PlaceDetailResponseDTO.swift
  Solply/Solply/Network/DTO/Place/ResponseDTO/PlaceRecommendResponseDTO.swift
  Solply/Solply/Network/DTO/Tags/RequestDTO/TagsRequestDTO.swift
  Solply/Solply/Network/DTO/Tags/ResponseDTO/MainTagsResponseDTO.swift
  Solply/Solply/Network/DTO/Tags/ResponseDTO/SubTagsResponseDTO.swift
  Solply/Solply/Network/Service/TagService.swift
  Solply/Solply/Network/Service/TagsService.swift
  Solply/Solply/Network/TargetType/TagTargetType.swift
  Solply/Solply/Network/TargetType/TagsTargetType.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveFullView.swift
  Solply/Solply/Presentation/Course/Component/CourseRecommendGrid.swift
  Solply/Solply/Presentation/Course/Component/DraggablePlaceCell.swift
  Solply/Solply/Presentation/Course/CourseDetail/Entity/PlaceDetailInCourse.swift
  Solply/Solply/Presentation/Course/CourseRecommend/Entity/CourseRecommend.swift
  Solply/Solply/Presentation/Place/Component/ChipButtonsContainerView.swift
  Solply/Solply/Presentation/Place/Component/FilterPlaceGrid.swift
  Solply/Solply/Presentation/Place/Component/MainTagBottomSheet.swift
  Solply/Solply/Presentation/Place/Component/SubTagBottomSheet.swift
  Solply/Solply/Presentation/Place/Component/SubTagChip.swift
  Solply/Solply/Presentation/Place/Component/SubTagHeader.swift
  Solply/Solply/Presentation/Place/Component/SubTagSection.swift
  Solply/Solply/Presentation/Place/Component/TodayPlaceRecommendCard.swift
  Solply/Solply/Presentation/Place/Component/View/PlaceInformationView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Entity/PlaceDetail.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailState.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Effect/PlaceRecommendEffect.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Entity/MainTag.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Entity/PlaceRecommend.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Entity/SubTag.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Intent/PlaceRecommendAction.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Intent/PlaceRecommendStore.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendReducer.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendState.swift
Labels: 🐰 jooyoung, 🛠️ feat

#184 [feat/#166] 내 코스의 추가 API 연동
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseAddPlaceResponseDTO.swift
  Solply/Solply/Network/Service/CourseService.swift
  Solply/Solply/Network/TargetType/CourseTargetType.swift
  Solply/Solply/Presentation/Course/CourseDetail/Effect/CourseDetailEffect.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Place/Component/View/AddPlaceToCourseView.swift
  Solply/Solply/Presentation/Place/Component/View/PlaceInformationView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Effect/PlaceDetailEffect.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailAction.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Intent/PlaceDetailStore.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailReducer.swift
  Solply/Solply/Presentation/Place/PlaceDetail/State/PlaceDetailState.swift
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
  Solply/Solply/Presentation/TabBar/TabBarView.swift
Labels: 🦒 seungwon, 🛠️ feat

#189 [feat/#185] 장소 리스트 조회 api 연결
  Solply/Solply/Global/Component/PlaceCard.swift
  Solply/Solply/Global/Enum/MainTagType.swift
  Solply/Solply/Network/DTO/Place/ResponseDTO/PlaceListResponseDTO.swift
  Solply/Solply/Network/Service/PlaceService.swift
  Solply/Solply/Network/TargetType/PlaceTargetType.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveListFullView.swift
  Solply/Solply/Presentation/Place/Component/FilterPlaceGrid.swift
  Solply/Solply/Presentation/Place/Component/SubTagBottomSheet.swift
  Solply/Solply/Presentation/Place/Component/TodayPlaceRecommendCarousel.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Effect/PlaceRecommendEffect.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Entity/Place.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Intent/PlaceRecommendAction.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Intent/PlaceRecommendStore.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendReducer.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendState.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/View/PlaceRecommendView.swift
Labels: 🐰 jooyoung, 🛠️ feat

#190 [feat/#188] 내 코스에 저장 API 연동
  Solply/Solply/Network/DTO/Course/RequestDTO/CourseCreateRequestDTO.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseCreateResponseDTO.swift
  Solply/Solply/Network/Service/CourseService.swift
  Solply/Solply/Network/TargetType/CourseTargetType.swift
  Solply/Solply/Presentation/Course/CourseDetail/Effect/CourseDetailEffect.swift
  Solply/Solply/Presentation/Course/CourseDetail/Entity/CourseDetail.swift
  Solply/Solply/Presentation/Course/CourseDetail/Entity/PlaceDetailInCourse.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailStore.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailState.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
Labels: 🦒 seungwon, 🛠️ feat

#193 [feat/#192] 코스 생성 API 연동
  Solply/Solply/Global/Extension/String+.swift
  Solply/Solply/Network/DTO/Course/RequestDTO/CourseCreateRequestDTO.swift
  Solply/Solply/Network/DTO/Course/RequestDTO/CourseUpdateRequestDTO.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseCreateResponseDTO.swift
  Solply/Solply/Network/DTO/Course/ResponseDTO/CourseUpdateResponseDTO.swift
  Solply/Solply/Network/Service/CourseService.swift
  Solply/Solply/Network/TargetType/CourseTargetType.swift
  Solply/Solply/Presentation/Course/CourseDetail/Effect/CourseDetailEffect.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailAction.swift
  Solply/Solply/Presentation/Course/CourseDetail/Intent/CourseDetailStore.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailReducer.swift
  Solply/Solply/Presentation/Course/CourseDetail/State/CourseDetailState.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
Labels: 🦒 seungwon, 🛠️ feat

#195 [feat/#180] 동네 선택 PATCH API 연결
  Solply/Solply/Network/DTO/User/RequestDTO/UserRequestDTO.swift
  Solply/Solply/Network/DTO/User/ResponseDTO/UserResponseDTO.swift
  Solply/Solply/Network/Service/TownService.swift
  Solply/Solply/Network/Service/UserService.swift
  Solply/Solply/Network/TargetType/UserTargetType.swift
  Solply/Solply/Presentation/Auth/Effect/AuthEffect.swift
  Solply/Solply/Presentation/Auth/Intent/AuthAction.swift
  Solply/Solply/Presentation/Auth/State/AuthReducer.swift
  Solply/Solply/Presentation/Auth/State/AuthState.swift
  Solply/Solply/Presentation/Auth/View/AuthView.swift
  Solply/Solply/Presentation/FrequentTown/Effect/FrequentTownEffect.swift
  Solply/Solply/Presentation/FrequentTown/Intent/FrequentTownAction.swift
  Solply/Solply/Presentation/FrequentTown/Intent/FrequentTownStore.swift
  Solply/Solply/Presentation/FrequentTown/State/FrequentTownReducer.swift
  Solply/Solply/Presentation/FrequentTown/State/FrequentTownState.swift
  Solply/Solply/Presentation/FrequentTown/View/FrequentTownView.swift
  Solply/Solply/Presentation/Onboarding/Component/View/NicknameView.swift
  Solply/Solply/Presentation/Onboarding/Component/View/OnboardingCompleteView.swift
  Solply/Solply/Presentation/Onboarding/Component/View/PersonaOptionView.swift
  Solply/Solply/Presentation/Onboarding/Component/View/TownOptionView.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingReducer.swift
Labels: ☀️ youngju, 🛠️ feat

#200 [fix/#194] 내 코스 추가 장소 선택 수정
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
Labels: 🦒 seungwon, ✂️ fix

#202 [hotfix]#197 favoritetownlist
  Solply/Solply/Network/DTO/User/RequestDTO/UserRequestDTO.swift
  Solply/Solply/Network/DTO/User/ResponseDTO/UserResponseDTO.swift
  Solply/Solply/Presentation/FrequentTown/Effect/FrequentTownEffect.swift
  Solply/Solply/Presentation/FrequentTown/Intent/FrequentTownStore.swift
Labels: ☀️ youngju, 🛠️ feat

#198 [feat/#157] 회원 정보 조회 api 연결
  Solply/Solply/Global/Component/PlaceCard.swift
  Solply/Solply/Global/Enum/PersonaType.swift
  Solply/Solply/Network/DTO/User/ResponseDTO/UserInformationResponseDTO.swift
  Solply/Solply/Network/Service/UserService.swift
  Solply/Solply/Network/TargetType/UserTargetType.swift
  Solply/Solply/Presentation/Course/CourseRecommend/View/CourseRecommendView.swift
  Solply/Solply/Presentation/Place/Component/FilterPlaceGrid.swift
  Solply/Solply/Presentation/Place/Component/TodayPlaceRecommendCarousel.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/View/PlaceRecommendView.swift
  Solply/Solply/Presentation/TabBar/TabBarView.swift
  Solply/Solply/Presentation/TabBar/UserInformation.swift
Labels: 🐰 jooyoung, 🛠️ feat

#205 [fix/#201] 1차 qa 반영
  Solply/Solply/Global/Component/TownOptionButton.swift
  Solply/Solply/Global/Enum/NavigationBarType.swift
  Solply/Solply/Global/Modifier/CustomNavigationBarModifier.swift
  Solply/Solply/Presentation/FrequentTown/View/FrequentTownView.swift
  Solply/Solply/Presentation/Onboarding/Component/View/NicknameView.swift
  Solply/Solply/Presentation/Onboarding/Component/View/PersonaOptionView.swift
  Solply/Solply/Presentation/Onboarding/Component/View/TownOptionView.swift
Labels: 🦒 seungwon, ✂️ fix

#203 [fix/#199] 장소 필터링 바텀시트 오류 수정
  Solply/Solply/Presentation/Place/Component/FilterPlaceGrid.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/Intent/PlaceRecommendAction.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendReducer.swift
  Solply/Solply/Presentation/Place/PlaceRecommend/State/PlaceRecommendState.swift
Labels: 🐰 jooyoung, ✂️ fix
