Repository SOLPLY/SOLPLY-iOS, pull requests merged in 2025-09, with the labels that each got.

#228 [refactor/#215] 지도뷰 자잘한 코드 수정
  Solply/Solply/Presentation/Course/Component/CourseDetailMapView.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Place/Component/View/PlaceDetailMapView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
Labels: 🦒 seungwon, 📎 chore

#222 [refactor/#217] 온보딩 API Protocol 적용
  Solply/Solply/Network/API/OnboardingAPI.swift
  Solply/Solply/Network/API/TownAPI.swift
  Solply/Solply/Network/API/UserAPI.swift
  Solply/Solply/Network/DTO/Onboarding/RequestDTO/OnboardingCompleteRequestDTO.swift
  Solply/Solply/Network/DTO/Onboarding/ResponseDTO/OnboardingCompleteResponseDTO.swift
  Solply/Solply/Network/DTO/Onboarding/ResponseDTO/OnboardingPersonaListResponseDTO.swift
  Solply/Solply/Network/DTO/Onboarding/ResponseDTO/OnboardingResponseDTO.swift
  Solply/Solply/Network/DTO/Town/ResponseDTO/TownListResponseDTO.swift
  Solply/Solply/Network/DTO/User/RequestDTO/UserTownsUpdateRequestDTO.swift
  Solply/Solply/Network/DTO/User/ResponseDTO/UserNicknameCheckResponseDTO.swift
  Solply/Solply/Network/DTO/User/ResponseDTO/UserResponseDTO.swift
  Solply/Solply/Network/DTO/User/ResponseDTO/UserTownsResponseDTO.swift
  Solply/Solply/Network/DTO/User/ResponseDTO/UserTownsUpdateResponseDTO.swift
  Solply/Solply/Network/Service/OnboardingService.swift
  Solply/Solply/Network/Service/TownService.swift
  Solply/Solply/Network/Service/UserService.swift
  Solply/Solply/Network/TargetType/OnboardingTargetType.swift
  Solply/Solply/Network/TargetType/TownTargetType.swift
  Solply/Solply/Network/TargetType/UserTargetType.swift
  Solply/Solply/Presentation/FrequentTown/Effect/FrequentTownEffect.swift
  Solply/Solply/Presentation/FrequentTown/Intent/FrequentTownStore.swift
  Solply/Solply/Presentation/Onboarding/Effect/OnboardingEffect.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingAction.swift
  Solply/Solply/Presentation/Onboarding/Intent/OnboardingStore.swift
  Solply/Solply/Presentation/Onboarding/State/OnboardingReducer.swift
Labels: ☀️ youngju, ✂️ fix, 🧤 refactor

#225 [refactor/#223] 수집함 custom alert 오타 수정
  Solply/Solply/Presentation/Archive/ArchiveList/View/ArchiveListView.swift
Labels: 🐳 sooyong, ✂️ fix, 🧤 refactor

#229 [feat/#224] AuthView UI 반영
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/apple-logo.imageset/Contents.json
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image-icon/apple-logo.imageset/apple-logo.svg
  Solply/Solply/Global/DesignSystem/Assets.xcassets/Image/login-graphic.imageset/login-graphic.svg
  Solply/Solply/Presentation/Auth/View/AuthView.swift
Labels: ☀️ youngju, 🛠️ feat

#232 [refactor/#230] 로띠 파일 변경
  Solply/Solply/Global/DesignSystem/Lottie/Splash.json
  Solply/Solply/Global/DesignSystem/Lottie/finishOnboarding.json
Labels: ☀️ youngju, 🧤 refactor

#236 [refactor/#234] 상세뷰 네비게이션바 플로팅 버튼으로 수정
  Solply/Solply/Global/Enum/NavigationBarType.swift
  Solply/Solply/Global/Modifier/CustomNavigationBarModifier.swift
  Solply/Solply/Presentation/Course/Component/CourseDetailMapView.swift
  Solply/Solply/Presentation/Course/Component/DraggablePlaceCell.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Place/Component/View/PlaceDetailMapView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/View/PlaceDetailView.swift
  Solply/Solply/Presentation/TabBar/Component/ArchiveButton.swift
Labels: 🦒 seungwon, 🧤 refactor

#241 [refactor/#231] 공통 컴포넌트 asset 수정사항 반영
  Solply/Solply/Global/Component/CourseCard.swift
  Solply/Solply/Global/Component/PlaceCard.swift
  Solply/Solply/Presentation/Archive/Component/ArchiveFullView.swift
Labels: 🐳 sooyong, 🧤 refactor

#245 [feat/#244] Auth 토큰 재발급 API
  Solply/Solply/Global/Security/Interceptor.swift
  Solply/Solply/Global/Security/TokenError.swift
  Solply/Solply/Network/API/AuthAPI.swift
  Solply/Solply/Network/Base/BaseService.swift
  Solply/Solply/Network/Base/BaseTargetType.swift
  Solply/Solply/Network/DTO/Auth/RequestDTO/AuthLoginRequestDTO.swift
  Solply/Solply/Network/DTO/Auth/ResponseDTO/AuthLoginResponseDTO.swift
  Solply/Solply/Network/DTO/Auth/ResponseDTO/AuthRefreshResponseDTO.swift
  Solply/Solply/Network/Service/AuthService.swift
  Solply/Solply/Network/TargetType/AuthTargetType.swift
  Solply/Solply/Network/TargetType/CourseTargetType.swift
  Solply/Solply/Network/TargetType/OnboardingTargetType.swift
  Solply/Solply/Network/TargetType/PlaceTargetType.swift
  Solply/Solply/Network/TargetType/RecommendTargetType.swift
  Solply/Solply/Network/TargetType/TagsTargetType.swift
  Solply/Solply/Network/TargetType/TownTargetType.swift
  Solply/Solply/Network/TargetType/UserTargetType.swift
  Solply/Solply/Presentation/Auth/Effect/AuthEffect.swift
  Solply/Solply/Presentation/Auth/Intent/AuthAction.swift
  Solply/Solply/Presentation/Splash/SplashView.swift
Labels: ☀️ youngju, 🛠️ feat

#261 [feat/#243] 동네 설정 UI 구현
  Solply/Solply/Global/Coordinator/Destination/AppDestination.swift
  Solply/Solply/Global/Modifier/CustomNavigationBarModifier.swift
  Solply/Solply/Presentation/FrequentTown/Component/JGDCityRow.swift
  Solply/Solply/Presentation/FrequentTown/Component/JGDTownRow.swift
  Solply/Solply/Presentation/FrequentTown/View/JGDView.swift
Labels: 🐰 jooyoung, 🛠️ feat

#270 [feat/#256] 제보하기 뷰 UI, 화면전환 구현, safeArea 문제 수정
  Solply/Solply/Global/Component/SolplyTextEditor.swift
  Solply/Solply/Global/Enum/NavigationBarType.swift
  Solply/Solply/Global/Enum/ReportsStep.swift
  Solply/Solply/Global/Modifier/CustomAlertModifier.swift
  Solply/Solply/Global/Modifier/CustomNavigationBarModifier.swift
  Solply/Solply/Presentation/Archive/Archive/View/ArchiveView.swift
  Solply/Solply/Presentation/Archive/ArchiveList/View/ArchiveListView.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/MyPage/View/MyPageView.swift
  Solply/Solply/Presentation/Place/PlaceDetail/Effect/PlaceDetailEffect.swift
  Solply/Solply/Presentation/Reports/Component/View/ReportsCompleteView.swift
  Solply/Solply/Presentation/Reports/Effect/ReportsEffect.swift
  Solply/Solply/Presentation/Reports/Intent/ReportsAction.swift
  Solply/Solply/Presentation/Reports/Intent/ReportsStore.swift
  Solply/Solply/Presentation/Reports/State/ReportsReducer.swift
  Solply/Solply/Presentation/Reports/State/ReportsState.swift
  Solply/Solply/Presentation/Reports/View/ReportsView.swift
  Solply/Solply/Presentation/TabBar/TabBarView.swift
Labels: 🦒 seungwon, ✂️ fix, 🛠️ feat

#273 [fix/#271] 상세 바텀시트 offset기반에서 frame기반으로 수정
  Solply/Solply/Global/Enum/CustomBottomSheetType.swift
  Solply/Solply/Global/Modifier/CustomBottomSheetModifier.swift
  Solply/Solply/Presentation/Course/CourseDetail/View/CourseDetailView.swift
  Solply/Solply/Presentation/Place/Component/View/PlaceInformationView.swift
Labels: 🦒 seungwon, ✂️ fix

#276 [fix/#274] 1차 qa 수정사항 반영
  Solply/Solply/Global/Modifier/LengthCheckModifier.swift
  Solply/Solply/Global/Util/DisableSwipeBackHelper.swift
  Solply/Solply/Presentation/Course/Component/CourseInformationEditBottomSheet.swift
  Solply/Solply/Presentation/Course/Component/CourseInformationEditTextField.swift
  Solply/Solply/Presentation/FrequentTown/View/JGDView.swift
  Solply/Solply/Presentation/Reports/Component/View/ReportsCompleteView.swift
  Solply/Solply/Presentation/Reports/View/ReportsView.swift
Labels: 🦒 seungwon, ✂️ fix
